/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gregelliott
 */
public class DiceGuessingGame extends javax.swing.JFrame {
    //Variables Used
    int totalRolls = 0;
    int totalCorrect =0;
    int totalIncorrect =0;
    int userGuess;
    int diceRoll;
    double percCorrect =0;

    public DiceGuessingGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblUserGuess = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        lblDiceRoll = new javax.swing.JLabel();
        lblRollValue = new javax.swing.JLabel();
        btnDiceRoll = new javax.swing.JButton();
        lblRolls = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lblHeader.setFont(new java.awt.Font("Optima", 0, 18)); // NOI18N
        lblHeader.setText("Super Dice Guessing Game");

        lblInst1.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblInst1.setText("Enter a number, from 1 to 6");

        lblInst2.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblInst2.setText("And click roll to roll the dice");

        lblUserGuess.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblUserGuess.setText("Your guess");

        txtUserGuess.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        txtUserGuess.setText("0");
        txtUserGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserGuessActionPerformed(evt);
            }
        });

        lblDiceRoll.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblDiceRoll.setText("Dice roll");

        lblRollValue.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblRollValue.setText("0");

        btnDiceRoll.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        btnDiceRoll.setText("Roll dice");
        btnDiceRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiceRollActionPerformed(evt);
            }
        });

        lblRolls.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblRolls.setText("Number of Rolls:");

        lblCorrect.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblCorrect.setText("Number of Correct Guesses:");

        lblIncorrect.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblIncorrect.setText("Number of Incorrect Guesses:");

        lblPercent.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblPercent.setText("Percentage of Correct Guesses:");

        lblRollsValue.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblRollsValue.setText("0");

        lblCorrectValue.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblCorrectValue.setText("0");

        lblIncorrectValue.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblIncorrectValue.setText("0");

        lblPercentValue.setFont(new java.awt.Font("Optima", 0, 13)); // NOI18N
        lblPercentValue.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblUserGuess))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorrect)
                            .addComponent(lblRolls)
                            .addComponent(lblIncorrect)
                            .addComponent(lblPercent))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnDiceRoll)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDiceRoll)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblRollValue)
                            .addGap(26, 26, 26)))
                    .addComponent(lblRollsValue)
                    .addComponent(lblCorrectValue)
                    .addComponent(lblIncorrectValue)
                    .addComponent(lblPercentValue))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInst1)
                    .addComponent(lblInst2)
                    .addComponent(lblHeader))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblHeader)
                .addGap(12, 12, 12)
                .addComponent(lblInst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserGuess)
                    .addComponent(lblDiceRoll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRollValue)
                            .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRolls)
                            .addComponent(lblRollsValue))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorrect)
                            .addComponent(lblCorrectValue))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncorrect)
                            .addComponent(lblIncorrectValue))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPercent)
                            .addComponent(lblPercentValue)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnDiceRoll)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserGuessActionPerformed

    private void btnDiceRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiceRollActionPerformed
       //Random Number Generator 
        diceRoll = (int)Math.round(Math.random()*5+1);
        lblRollValue.setText(String.valueOf(diceRoll));
        
        //User Guess
        userGuess = Integer.parseInt(txtUserGuess.getText());
        
        //Scoring, you get a point if you guess the right number of the dice Roll
        totalRolls=totalRolls+1;
        
        if (diceRoll==userGuess)
        {
            totalCorrect= totalCorrect+1;
        }
        else
        {
            totalIncorrect=totalIncorrect+1;
        }
        percCorrect=((double)totalCorrect/(double)totalRolls)*100;
        
        //Percent Correct of correct guesses
        percCorrect=percCorrect*100;
        percCorrect=Math.round(percCorrect);
        percCorrect=percCorrect/100;
        
        //Values outpted to the user
        lblRollValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percCorrect));
        
    }//GEN-LAST:event_btnDiceRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiceRoll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblDiceRoll;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollValue;
    private javax.swing.JLabel lblRolls;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblUserGuess;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
